Indicator Component
IRCC-ca/ds-sdc-dev pull request #130
Opened 2023-03-15 18:49 UTC by xingruoxicic

2023-03-15 20:24 UTC, MikeJalow requested changes

2023-03-15 20:24 UTC, MikeJalow commented on core-library/component-styling/indicator/_indicator.scss
> +    border-radius: 50% !important;
is there any way we could avoid using !important? We'd ideally never use this in our DS.

2023-03-15 20:24 UTC, MikeJalow commented on core-library/component-styling/indicator/_indicator.scss
> +    color: color.mix-token(neutral, 900);
these mix-tokens will need to moved to a fresh token sheet - if we don't it'll cause issues when we're trying to integrate dark mode.

2023-03-16 13:47 UTC, kristopher-houston commented on component-library/component-lib/src/lib/shared/indicator/indicator.component.ts
> +  constructor() { }
Remove if not used

2023-03-16 15:12 UTC, kristopher-houston approved these changes

2023-03-20 19:24 UTC, kristopher-houston commented on component-library/component-lib/src/lib/shared/indicator/indicator.component.ts
> +  ngOnInit(): void {
Remove ': void'

2023-03-20 19:24 UTC, kristopher-houston commented on component-library/component-lib/src/lib/shared/indicator/indicator.component.ts
> +  ngOnChanges(changes: SimpleChanges): void {
Remove ': void'

2023-03-21 19:39 UTC, MikeJalow approved these changes

2023-03-21 19:40 UTC, merged